language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy

install:
  - pip install coveralls
  - pip install pytest-cov
  - pip install .

script:
  - py.test --cov-report term --cov jcconv jcconv/jcconv_test.py

after_success:
  - coveralls
