language: python

python:
  - 2.5
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

install:
  - pip install coveralls
  - pip install .

script:
  - nosetests --with-coverage

after_success:
  - coveralls
